services:
  - type: web
    name: reconocimiento-facial-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn api.main_api:app --host 0.0.0.0 --port $PORT"
